# Generated by Django 4.1.7 on 2023-03-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=50)),
                ('electricity_past', models.IntegerField(default='0')),
                ('electricity_current', models.IntegerField(default='0')),
                ('water_past', models.IntegerField(default='0')),
                ('water_current', models.IntegerField(default='0')),
                ('electricity_tariff', models.FloatField(default='0')),
                ('water_tariff', models.FloatField(default='0')),
            ],
        ),
    ]
